"""empty message

Revision ID: 6b21b462d02a
Revises: 9a822d71c585
Create Date: 2021-05-15 11:11:26.302140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b21b462d02a'
down_revision = '9a822d71c585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('priority_level', sa.String(), nullable=True))
    # Update existing records with default values
    op.execute("UPDATE todos SET priority_level = 'low'")
    op.alter_column('todos', 'priority_level', nullable=False)
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_column('todos', 'priority_level')
    op.drop_table('todolists')
    # ### end Alembic commands ###
