"""empty message

Revision ID: 7db989ca095a
Revises: 9d0375ec4c87
Create Date: 2021-05-13 18:11:21.580852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db989ca095a'
down_revision = '9d0375ec4c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority_level', sa.String(), nullable=True))
    # Update existing records with default values
    op.execute("UPDATE todos SET priority_level = 'low'")
    op.alter_column('todos', 'priority_level', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'priority_level')
    # ### end Alembic commands ###
