"""empty message

Revision ID: 9a822d71c585
Revises: 7db989ca095a
Create Date: 2021-05-15 10:58:47.436702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a822d71c585'
down_revision = '7db989ca095a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO todolists (name) VALUES 'Uncategorised'")
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.execute("UPDATE todos SET list_id = 0")
    #op.alter_column('todos', 'list_id', nullable=False)
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
